language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

install:
  - composer install

script:
  - phpunit
  - phpunit test/CommonMarkTestWeak.php || true
